- alias: Sourdough feed due soon
  triggers:
    - trigger: state
      entity_id: binary_sensor.main_starter_feed_due_soon
      to: "on"
  actions:
    - action: notify.mobile_app_your_phone
      data:
        title: Sourdough starter
        message: Your starter will be due for feeding soon.

- alias: Sourdough feed overdue
  triggers:
    - trigger: state
      entity_id: binary_sensor.main_starter_feed_due
      to: "on"
  actions:
    - action: notify.mobile_app_your_phone
      data:
        title: Sourdough starter
        message: Your starter is due to be fed.
